name: First workflow
on: workflow_dispatch
jobs:
  first_job:
    runs_on: ubuntu_latest
    steps:
      - name: Print Greetings
        run: echo "Hello world!"
      - name: Print Goodbye
        run: echo "Done -byee!"
